### ISSUE TITLE
説明用のテキストを作る

### ISSUE THREAD

**Issue by snakazawa** [swkoubou/alcoholic-mine#57]

**Comment by NISHI3** [comment]
GAME STARTを押してますと、ユーザー名の入力が出てくるので入れて下さい、
次に10秒間パネルが出てきますので覚えて下さい。
10秒後パネルが全て白になります。
プレイヤーはターンごとにゲームマスターが指示する色のパネルを記憶を頼りに押して下さい。
プレイヤーが全てのパネルを埋めるとプレイヤーの勝ちです。
プレイヤーが間違ったパネルを押すとプレイヤーの負けです。
負けたプレイヤーには罰ゲームが有ります。

**Comment by snakazawa** [comment]
10秒とは限らない
ゲームマスターが全て開かれているパネルの色を選択すると、ゲームマスターの負け
罰ゲームがあるわけではないような気がする
ゲームマスター vs プレイヤー（複数）　であることが分かるテキストも入れてほしい
1行目は要らない（ゲーム自体の説明だけでOK）
画像が必要そうなら指示してください

**Comment by NISHI3** [comment]
数秒間パネルが出てきますので覚えて下さい。
数秒後パネルが全て白になります。
プレイヤーはターンごと順番にゲームマスターが指示する色のパネルを記憶を頼りに押して下さい。
全てのプレイヤーが指定した色のパネルを全て開くと、プレイヤーの勝ちです。
一人のプレイヤーが間違った色のパネルを開くと、そのプレイヤーの負けです。
ゲームマスターはすでに全て開かれているパネルの色を選択すると、ゲームマスターの負けです。

**Comment by snakazawa** [comment]
"数秒間パネルが出てきますので覚えて下さい。"  => "最初に数秒間パネルが出てきますので覚えて下さい。"
"全てのプレイヤーが指定した色のパネルを全て開くと、" => "プレイヤーが全てのパネルを開くと、"
"ゲームマスターはすでに" => "ゲームマスターがすでに"

**Comment by snakazawa** [comment]
なんかわかり辛い > "プレイヤーはターンごと順番にゲームマスターが指示する色のパネルを記憶を頼りに押して下さい。"

**Comment by NISHI3** [comment]
最初の数秒間パネルが出てきますので覚えて下さい。
数秒後パネルが全て白になります。
プレイヤーはターンごとにゲームマスターが指定する色のパネルを開いて下さい。
プレイヤーが全てのパネルを全て開くと、プレイヤーの勝ちです。
一人のプレイヤーが間違った色のパネルを開くと、そのプレイヤーの負けです。
ゲームマスターがすでに全て開かれているパネルの色を選択すると、ゲームマスターの負けです。

**Comment by snakazawa** [comment]
"最初の数秒間パネルが出てきますので覚えて下さい。" => "最初の数秒間パネルが表示されるので、色と配置を覚えて下さい。"

**Comment by snakazawa** [comment]
"全てのパネルを全て開くと"

**Comment by snakazawa** [comment]
"一人" って言わなくてもいい気がする

**Comment by snakazawa** [comment]
"指定" で統一しよう
"ゲームマスターがすでに全て開かれているパネルの色を選択" => "ゲームマスターがすでに全て開かれているパネルの色を指定"

**Comment by NISHI3** [comment]
最初の数秒間パネルが表示されるので、色と配置を覚えて下さい。
数秒後パネルが全て白になります。
プレイヤーはターンごとにゲームマスターが指定する色のパネルを開いて下さい。
プレイヤーが全てのパネルを開くと、プレイヤーの勝ちです。
プレイヤーが間違ったパネルを開くと、プレイヤーの負けです。
ゲームマスターがすでに全て開かれているパネルの色を指定すると、ゲームマスターの負けです。

”プレイヤーが間違った色のパネルを”だと、配置を含めた意味ではない気がしたので、”間違ったパネル”に変更しました。

**Comment by snakazawa** [comment]
最初の数秒間パネルが表示されるので、色と配置を覚えて下さい。
数秒後パネルが全て白になります。
プレイヤーはターンごとにゲームマスターが指定する色のパネルを開いて下さい。
プレイヤーが間違ったパネルを開くと、プレイヤーの負けです。
プレイヤーが全てのパネルを開くか、ゲームマスターがすでに全て開かれているパネルの色を指定すると、ゲームマスターの負けです。
