### ISSUE TITLE
設定変更後すすまない

### ISSUE THREAD

**Issue by kaito-akt** [swkoubou/alcoholic-mine#89]
ゲームを一度やってから設定変更後"ゲームスタート"及び"設定"、"ゲーム説明"をタップしても進まない。

エラーメッセージ
game.js:79 Uncaught TypeError: Cannot read property 'turnIndex' of undefined

**Comment by snakazawa** [comment]
再現できない...

**Comment by kaito-akt** [comment]
普通にできますね...

**Comment by snakazawa** [comment]
でも機能デモの時挙動おかしいことがあったのは確かなんだよなぁ（BGMがおかしいのは直した）
まぁClose！
